apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skeleton-certificate
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "skeleton.name" . }}
    helm.sh/chart: {{ include "skeleton.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ default "do-block-storage" .Values.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skeleton-static-files
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "skeleton.name" . }}
    helm.sh/chart: {{ include "skeleton.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ default "do-block-storage" .Values.storageClassName }}