kind: Service
apiVersion: v1
metadata:
  name:  skeleton-server
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "skeleton.name" . }}
    helm.sh/chart: {{ include "skeleton.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app:  skeleton-server
  type:  NodePort
  ports:
    - name:  http
      port:  80
      targetPort:  80
    - name:  php-fpm
      port:  9000
      targetPort:  9000